#!/bin/bash
VERSION="1.3.10"

TAGS=$(echo $VERSION | sed -e 's/^\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/\1.\2.\3 \1.\2 \1/')
echo $TAGS
for f in $TAGS
do
	NEW_IMAGE_NAME="$DOCKER_REPO:$f"
	echo "Tagging: $DOCKER_REPO:$f"
	docker tag $IMAGE_NAME $NEW_IMAGE_NAME
	docker push $NEW_IMAGE_NAME
done
